config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :valera_actions do
    resources :conditions
  end
  resource :session
  resources :valera_actions
  resources :users
  resources :stats_records

  root 'home#index'
end

app/models/condition.rb
class Condition < ApplicationRecord
  belongs_to :valera_action
end

app/controllers/conditions_controller.rb
class ConditionsController < ApplicationController
  def show
    @valera_action = ValeraAction.find(params[:valera_action_id])
    @condition = @valera_action.conditions.find(params[:id])
  end

  def new
    @valera_action = ValeraAction.find(params[:valera_action_id])
    @condition = Condition.new
  end

  def edit
    @valera_action = ValeraAction.find(params[:valera_action_id])
    @condition = @valera_action.conditions.find(params[:id])
  end

  def create
    @valera_action = ValeraAction.find(params[:valera_action_id])
    @condition = @valera_action.conditions.create(condition_params)
    redirect_to valera_action_path(@valera_action)
  end

  def update
    @valera_action = ValeraAction.find(params[:valera_action_id])
    @condition = @valera_action.conditions.find(params[:id])

    @condition.update(condition_params)

    redirect_to valera_action_path(@valera_action)
  end

  def destroy
    @valera_action = ValeraAction.find(params[:valera_action_id])
    @condition = @valera_action.conditions.find(params[:id])
    @condition.destroy
    redirect_to valera_action_path(@valera_action)
  end

  private

  def condition_params
    params.require(:condition).permit!
  end
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/views/conditions/_condition.html.erb
<div class="">
  <div>
    <p>
      <strong>Condition:</strong>
      <strong>attr_name:</strong>
      <%= condition.attr_name %><br><br>
      <strong>min:</strong>
      <%= condition.min %><br><br>
      <strong>max:</strong>
      <%= condition.max %><br><br>
      <strong>attr_name_eff:</strong>
      <%= condition.attr_name_eff %>
      <strong>value_eff:</strong>
      <%= condition.value_eff %>
    </p>
  </div>
  <%= link_to 'Редактировать', edit_valera_action_condition_path(condition.valera_action, condition), class: "" if user_signed_in?() %>
  <%= link_to 'Убрать', [condition.valera_action, condition], class: "",
              method: :delete,
              data: { confirm: 'Are you sure?' } if user_signed_in?() %>
</div>

app/views/conditions/_form.html.erb
<div class="editForm">
  <%= form_with model: [ @valera_action, @condition ], local: true do |form| %>
    
    <p>
      <%= form.label :attr_name %><br>
      <%= form.select :attr_name, ['none', 'health', 'alcohol', 'happy', 'tired', 'money'], class: "editTextField" %>
    </p>
    <p>
      <%= form.label :min %><br>
      <%= form.number_field :min, class: "editTextField" %>
    </p>
    <p>
      <%= form.label :max %><br>
      <%= form.number_field :max, class: "editTextField" %>
    </p>
    <p style="display:flex;">
      <%= form.label :attr_name_eff %><br>
      <%= form.select :attr_name_eff, ['none', 'health', 'alcohol', 'happy', 'tired', 'money'], class: "editTextField" %>
    </p>  
    <p>
      <%= form.label :value_eff %><br>
      <%= form.number_field :value_eff, class: "editTextField" %>
    </p>
    <p>
      <%= form.submit class: "submitForm" %>
    </p>
  <% end %>
</div>

app/views/conditions/edit.html.erb
<div class="titlePage">Редактирование предмета одежды</div>
 
<%= render 'form' %>
 
<%= link_to 'Назад', valera_action_path(@valera_action), class: "editBackLink" %>

app/views/conditions/new.html.erb
<div class="titlePage" id="titleForm">Добавить cond</div>
 
<%= render 'form' %>
 
<%= link_to 'Назад', valera_action_path(@valera_action), class: "editBackLink" %>