config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :valera_actions do
    resources :conditions
  end
  resource :session
  resources :valera_actions
  resources :users
  resources :stats_records

  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  # rubocop:disable Rails/UniqueValidationWithoutIndex
  validates :email, presence: true, uniqueness: true
  # rubocop:enable Rails/UniqueValidationWithoutIndex
  validates :name, presence: true

  validates :health, numericality: { only_integer: true }
  validates :alcohol, numericality: { only_integer: true }
  validates :happy, numericality: { only_integer: true }
  validates :tired, numericality: { only_integer: true }
  validates :money, numericality: { only_integer: true }
  # rubocop:disable Rails/HasManyOrHasOneDependent
  has_one :stats_record
  # rubocop:enable Rails/HasManyOrHasOneDependent
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  def show
    @user = User.find(params[:id])
    save_max_stat
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    new_stat!(@user)
    user_save
  end

  def edit
    if user_signed_in?
      @user = User.find(params[:id])
    else
      redirect_to @user
    end
  end

  def update
    if user_signed_in?
      @user = User.find(params[:id])
      user_update
    else
      redirect_to @user
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end

  def user_save
    if @user.save
      log_in @user
      save_max_stat
      redirect_to @user
    else
      render 'new'
    end
  end

  def user_update
    action_effect = params[:user].permit!
    if action_effect['action_id'] == 'New game'
      new_stat!(@user)
    else
      do_action action_effect
    end
    user_save
  end

  def do_action(action_effect)
    conds = ValeraAction.find(action_effect['action_id']).conditions
    if action_available?(conds)
      select_effects!(conds, action_effect, @user)
      updated_stat = stats_update(action_effect, @user)
      validate_stats!(updated_stat, @user)
      @user.update(updated_stat)
      flash.notice = 'You died.' if dead?(@user)
    else
      flash.notice = 'You cannot do it.'
    end
  end

  def action_available?(conds)
    conds.each do |cond|
      next unless cond.attr_name_eff == 'none'

      unless cond_is_true?(cond, @user)
        flash.alert = "Your '#{cond.attr_name}' should be between #{cond.min} and #{cond.max}."
        return false
      end
    end
    true
  end

  def save_max_stat
    if StatsRecord.exists?(@user.id)
      @stats_record = StatsRecord.find(@user.id)
      @stats_record.money = [@stats_record.money, @user.money].max
    else
      @stats_record = StatsRecord.create(id: @user.id, name: @user.name, money: @user.money)
    end
    @stats_record.save!
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def new_stat!(user)
    user.health = 100
    user.alcohol = 0
    user.happy = 0
    user.tired = 0
    user.money = 300
  end

  def stats_update(action_effect, user)
    updated_stat = { 'health' => 0, 'alcohol' => 0, 'happy' => 0, 'tired' => 0, 'money' => 0 }
    updated_stat.each { |key, _value| updated_stat[key] = action_effect[key].to_i + user[key] }
    updated_stat
  end

  def select_effects!(conds, action_effect, user)
    conds.each do |cond|
      action_effect[cond.attr_name_eff] = cond.value_eff if (cond.attr_name_eff != 'none') && cond_is_true?(cond,
                                                                                                            user)
    end
  end

  def cond_is_true?(condition, user)
    user[condition.attr_name].between?(condition.min, condition.max) unless condition.nil?
  end

  def dead?(user)
    user.health.zero? || user.happy == -10 || user.money <= -100 || user.tired == 100
  end

  def validate_stats!(stats, user)
    stats['health'] = valid_health(stats['health'])
    stats['alcohol'] = valid_alcohol(stats['alcohol'], user)
    stats['happy'] = valid_happy(stats['happy'])
    stats['tired'] = valid_tired(stats['tired'])
  end

  def valid_health(health)
    validate(health, 0, 100)
  end

  def valid_alcohol(alcohol, user)
    user.health -= validate(user.alcohol - alcohol, 0, user.health) if user.alcohol < alcohol.abs
    validate(alcohol, 0, 100)
  end

  def valid_happy(happy)
    validate(happy, -10, 10)
  end

  def valid_tired(tired)
    validate(tired, 0, 100)
  end

  def validate(value, min, max)
    [[value, max].min, min].max
  end
end

app/views/users/_form.html.erb
<div class="editForm">
<%= form_with model: @user, local: true do |form| %>

  <div id="error_explanation">
    <% if @user.errors.any? %>
      <%= pluralize(@user.errors.count, "error") %> prohibited
      this user from being saved:
          
      <% @user.errors.full_messages.each do |msg| %>
        <div> <%= msg %> </div>
      <% end %>
    <% end %>
  </div>
  <div>
    <p>
      <%= form.label :email %><br>
      <%= form.email_field :email, :required=>true, class: "editTextField" %> 
    </p>
    <p>
        <%= form.label :name %><br>
        <%= form.text_field :name, class: "editTextField" %>
    </p>
    <p>
      <%= form.label :password %><br>
      <%= form.password_field :password,:required=>true, class: "editTextField" %>
    </p>
    <p>
      <%= form.label :password_confirmation %><br>
      <%= form.password_field :password_confirmation, :required=>true, class: "editTextField" %>
    </p>
    <p>
      <%= form.submit class: "submitForm" %>
    </p>
  </div> 
<% end %>
</div>

app/views/users/_new_game.html.erb
<%= form_with(model: @user, method: "patch") do |f| %>
      <div class >
        <%= f.hidden_field :action_id, value: "New game"%>
        <%= f.submit "New game"%>
      </div>
<% end %>

app/views/users/new.html.erb
<div class="titlePage" id="titleForm">Регистрация</div>
 
<%= render 'form' %>

<%= link_to 'Назад', root_path, class: "editBackLink" %>

app/views/users/records.htm.erb
<div class="titlePage">Records</div>

<div class="">
  <% @users.each.stats_record do |stats_record| %>
    <div class="">
    <%= stats_record.id; stats_record.name; stats_record.money %>
    </div>

  <% end %>
</div>

app/views/users/show.html.erb
<%= link_to 'LOG OUT', session_path, data: { method: :delete }, class: "logButtons" %>
<%= link_to 'Records', stats_records_path, class: "logButtons" %>

<%= render 'new_game' %>
<div class="listCards">
  <div class="cart">
    <strong>Health:</strong>
    <%= @user.health%>/100<br><br>
  </div>
  <div class="cart">
    <strong>Alcohol:</strong>
      <%= @user.alcohol%>/100<br><br>
  </div>
  <div class="cart">
    <strong>Happy:</strong>
      <%= @user.happy%>/10<br><br>
  </div>
  <div class="cart">
    <strong>Tired:</strong>
      <%= @user.tired%>/100<br><br>
  </div>
  <div class="cart">
    <strong>Money:</strong>
      <%= @user.money%>$<br><br>
  </div>
      
</div>
<div class="closebtn">
      <% flash.each do |type, msg| %>
        <div class="alert alert-info">
          <%= msg %>
          <%= render 'new_game' if msg == "You died."%>
        </div>
      <% end %>
</div>
      
        <%= render 'valera_actions/index'%><br><br>