config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :valera_actions do
    resources :conditions
  end
  resource :session
  resources :valera_actions
  resources :users
  resources :stats_records

  root 'home#index'
end

app/controllers/valera_actions_controller.rb
class ValeraActionsController < ApplicationController
  def index
    @valera_actions = ValeraAction.all
  end

  def show
    @valera_action = ValeraAction.find(params[:id])
  end

  def new
    @valera_action = ValeraAction.new
  end

  def edit
    if user_signed_in?
      @valera_action = ValeraAction.find(params[:id])
    else
      redirect_to user_path(current_user)
    end
  end

  def create
    if user_signed_in?
      @valera_action = ValeraAction.new(valera_action_params)
      valera_action_save
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    if user_signed_in?
      @valera_action = ValeraAction.find(params[:id])
      valera_action_update
    else
      redirect_to user_path(current_user)
    end
  end

  def destroy
    if user_signed_in?
      @valera_action = ValeraAction.find(params[:id])
      @valera_action.destroy
    end
    redirect_to user_path(current_user)
  end

  private

  def valera_action_params
    params.require(:valera_action).permit(:name, :health, :alcohol, :happy, :tired, :money)
  end

  def valera_action_save
    if @valera_action.save
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end

  def valera_action_update
    if @valera_action.update(valera_action_params)
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end
end

app/helpers/valera_actions_helper.rb
module ValeraActionsHelper
end

app/views/valera_actions/_form.html.erb
<%= form_with model: @valera_action, local: true do |form| %>
 
  <% if @valera_action.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@valera_action.errors.count, "error") %> prohibited
        this valera_action from being saved:
      </h2>
      <ul>
        <% @valera_action.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="editForm">
    <p>
      <%= form.label :name %>
      <%= form.text_field :name, class: "editTextField" %>
    </p>
    <p>
      <%= form.label :health %>
      <%= form.number_field :health, class: "editTextField" %>
    </p>
    <p>
      <%= form.label :alcohol %>
      <%= form.number_field :alcohol, class: "editTextField" %>
    </p>
    <p>
      <%= form.label :happy %>
      <%= form.number_field :happy, class: "editTextField" %>
    </p>
    <p>
      <%= form.label :tired %>
      <%= form.number_field :tired, class: "editTextField" %>
    </p>
    <p>
      <%= form.label :money %>
      <%= form.number_field :money, class: "editTextField" %>
    </p>
  </div>

  <%= form.submit class: "submitForm" %>

 
<% end %>

app/views/valera_actions/_index.html.erb
<strong class ="titlePage">Actions:</strong>
<%= render 'valera_actions/list' %>

app/views/valera_actions/_list.html.erb
<div class="">
  <%= link_to 'Add action', new_valera_action_path, class: "" if user_signed_in?() %>
  <% ValeraAction.all.each do |valera_action| %>
    <%= form_with(model: @user, method: "patch", remote: true) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user valera from being saved:</h2>
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div  class="button">
        <%= f.hidden_field :action_id, value: valera_action.id %>
        <%= f.hidden_field :health, value: valera_action.health %>
        <%= f.hidden_field :alcohol, value: valera_action.alcohol %>
        <%= f.hidden_field :happy, value: valera_action.happy %>
        <%= f.hidden_field :tired, value: valera_action.tired %>
        <%= f.hidden_field :money, value: valera_action.money %>

      <%= f.submit valera_action.name%>
      </div>
      
    <% end %>
    
    <%= link_to 'Show', valera_action_path(valera_action), class: "" if user_signed_in?()%>
    <%= link_to 'Edit', edit_valera_action_path(valera_action), class: "" if user_signed_in?()%>
    <%=  link_to 'Delete', valera_action_path(valera_action), class: "",
                method: :delete,
                data: { confirm: 'Are you sure?' } if user_signed_in?()%>
  <% end %>
</div>

app/views/valera_actions/edit.html.erb
<div class="titlePage">Редактирование категории</div>
 
<%= render 'form' %>
 
<%= link_to 'Back', user_path(current_user), class: "editBackLink" %>

app/views/valera_actions/new.html.erb
<div class="titlePage">Новая категория</div>
 
<%= render 'form' %>
 
<%= link_to 'Back', root_path, class: "editBackLink" %>

app/views/valera_actions/show.html.erb
<div class="titlePage"> <%= @valera_action.name %> </div>


<div class="">
  <%= render @valera_action.conditions %>
</div>

<%= link_to "Add", new_valera_action_condition_path(@valera_action, @valera_action.conditions.build),
    class: "topBarLink", id: "addLink" if user_signed_in?() %>
<%= link_to "Back", user_path(current_user), class: "topBarLink", id: "backLink" %>